# Generated by Django 4.2.4 on 2023-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='SiteBox',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='brochure_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
