# Generated by Django 4.2.4 on 2023-08-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_navigation_page_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
